# This file is the base, which at a minimum should work on gh-pages
# When building locally for development or production, pass in the environment config:
#
# GitHub Pages Automated Build: Uses _config.yml
#
# Development Serve: jekyll serve --config _config.yml,_config.dev.yml
#
# Production Build: jekyll build --config _config.yml,_config.prod.yml

title: BBIS Developer Documentation
baseurl: /developer.blackbaud.com-bbis
highlighter: pygments
permalink: /404.html
compress: true
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

css:
  - url: //maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css
    base: false
    
  - url: //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
    base: false

  - url: /assets/lib/owl-carousel-v2/assets/owl.carousel.min.css
    base: true
    
  - url: /assets/lib/owl-carousel-v2/assets/owl.theme.default.min.css
    base: true
    
  - url: /assets/css/blackbaud-bootstrap-theme.css
    base: true
    
  - url: /assets/lib/animate/animate.css
    base: true
  
  - url: /assets/css/syntax.css
    base: true
  
  - url: /assets/css/app.css
    base: true

js:
  - url: //code.jquery.com/jquery-1.11.1.min.js
    base: false
    
  - url: //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js
    base: false
    
#  - url: //cdnjs.cloudflare.com/ajax/libs/easyXDM/2.4.17.1/easyXDM.min.js
#    base: false
#    
#  - url: //signin.blackbaud.com/omnibar.js
#    base: false
    
  - url: /assets/lib/owl-carousel-v2/owl.carousel.min.js
    base: true
    
  - url: /assets/js/owl.feature.js
    base: true
    
  - url: /assets/lib/zero-clipboard/ZeroClipboard.min.js
    base: true
    
  - url: /assets/js/blackbaud-bootstrap-theme.js
    base: true
    
  - url: /assets/js/app.js
    base: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      sidebar: ""
      carousel: false